apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-app-ingress
  namespace: booking-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: booking.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: booking-app-service
                port:
                  number: 80
